# -*- coding: utf-8 -*-
"""NLP -NER - Named_Entity_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dbpz3I-t3ze3_7k7zbemeUOCJYwlBeS9
"""

!pip install spacy--upgrade
#pip install spacy==version
!python -m spacy download pt
!python install nltk --upgrade

import spacy
from nltk.stem import PorterStemmer
from spacy import displacy
spacy.__version__, nltk.__version__

nlp = spacy.load('pt')
document = nlp('I\'m learning English... in Brazil')

for token in document:
  print(token.text, token.pos_)

for token in document:
  print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape, token.is_alpha, token.is_stop)

for token in document:
   if token.pos == 'PROPN':
    print(token.text)

for token in document:
   if token.pos == 'PROPN':
    print(token.text, token.lemma_)

doc = nlp('am  is are be was were')
[token.lemma_ for token in doc]

stemmer = PorterStemmer()
stemmer.stem('am')

for token in document:
   if token.pos == 'PROPN':
    print(token.text, token.lemma_, stemmer.stem(token.text))

text = "IBM... Recife..."

doc = nlp(text)

for entity in doc:
   print(entity.text, entity.label_)

displacy.render(doc, style = 'ent', jupyter = True)

text2 = "Luiz Gonzaga... Exu... Baião"

doc = nlp(text2)

for entity in doc:
   print(entity.text, entity.label_)

displacy.render(doc, style = 'ent', jupyter = True)

for entity in doc.ents:
   if entity.label == 'PER'
    print(entity.text)