# -*- coding: utf-8 -*-
"""NLP - Lemmatization_Stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rf8ih1Ke71gwA-R1ffeQaR2RdE_eJHl2
"""

!pip install spacy--upgrade
#pip install spacy==version
!python -m spacy download pt
!python install nltk --upgrade

import spacy
from nltk.stem import PorterStemmer
spacy.__version__, nltk.__version__

nlp = spacy.load('pt')
document = nlp('I\'m learning English... in Brazil')

for token in document:
  print(token.text, token.pos_)

for token in document:
  print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape, token.is_alpha, token.is_stop)

for token in document:
   if token.pos == 'PROPN':
    print(token.text)

for token in document:
   if token.pos == 'PROPN':
    print(token.text, token.lemma_)

doc = nlp('am  is are be was were')
[token.lemma_ for token in doc]

stemmer = PorterStemmer()
stemmer.stem('am')

for token in document:
   if token.pos == 'PROPN':
    print(token.text, token.lemma_, stemmer.stem(token.text))