# -*- coding: utf-8 -*-
"""NLP - Part of Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FiO8cE3N2GF0sy6QWiuefV2zB0-zlMn
"""

!pip install spacy--upgrade
#pip install spacy==version
!python -m spacy download pt

import spacy
spacy.__version__

nlp = spacy.load('pt')
document = nlp('I\'m learning English... in Brazil')

for token in document:
  print(token.text, token.pos_)

for token in document:
  print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape, token.is_alpha, token.is_stop)

for token in document:
   if token.pos == 'PROPN':
    print(token.text)